// <auto-generated />
using System;
using AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Escolapios.Migrations
{
  [DbContext(typeof(AppDBContext))]
  partial class ContextDBModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.4")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Context.Models.Payment", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("IdentificationNumber")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<long?>("PaymentId")
                      .HasColumnType("bigint");

            b.HasKey("Id");

            b.ToTable("PaymentTable");
          });
#pragma warning restore 612, 618
    }
  }
}
