import { Work_Sans, Alegreya } from "next/font/google";
import Header from "@/components/widgets/header";
import type { Metadata } from "next";
import "./globals.css";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={workSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
